### ISSUE TITLE
Add Content Overview In Readme.md

### ISSUE THREAD

**Issue by jmwright** [Mach30/dof#1]
Having at least a description of the theme of each directory would help. Right now there are just the `core-assumptions` and `use-cases` directories.

**Comment by m30-jrs** [comment]
I am actually in the process of completely restructuring this repo.  As part of that work I will be adding descriptions of each of the directories and how to use them plus generating the top level readme and the architecture document.

**Comment by m30-jrs** [comment]
@jmwright - my plan is to migrate material over to the architecture yaml files and then retire the old content from the repo.  Assuming this is done in concert with the production docs about the yaml file formats and the final architecture documentation, would you feel this issue is being addressed enough to close it?

**Comment by jmwright** [comment]
Yep. I think this has a good direction set already.
